services:
  - type: web
    name: rail-crossing-ostroda-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PLK_API_KEY
        sync: false
      - key: NOTIFY_TICK_SECRET
        sync: false
